# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Collections - might want to auto generate this
collections_dir: _collections
collections:
  pages:
    output: true
    permalink: /:title
  events:
    output: true
  menu: 
    output: true
    permalink: /menu/:title
  locations:
    output: true
  blog:
    output: true
  careers:
    output: true
defaults:
  -
    scope:
      type: "pages"
    values:
      layout: page
  -
    scope:
      path: "index.md"
    values:
      layout: home
  -
    scope:
      path: "_pages/blog.md"
    values:
      layout: blog
  - 
    scope:
      type: blog
    values:
      layout: blogitem
  -
    scope:
      path: "_pages/menu.md"
    values:
      layout: menu
  - 
    scope:
      type: "menu"
    values:
      layout: menuitem
  -
    scope:
      path: "_pages/events.md"
    values:
      layout: events
  - 
    scope:
      path: ""
      type: "events"
    values:
      layout: eventitem
  - 
    scope:
      path: "_pages/locations.md"
    values:
      layout: locations
  - 
    scope:
      path: ""
      type: "locations"
    values:
      layout: locationitem
  - 
    scope:
      path: "_pages/careers.md"
    values:
      layout: careers
  - 
    scope:
      path: ""
      type: "careers"
    values:
      layout: careeritem
 
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
